# My custom aliases
alias ttytter='$HOME/bin/ttytter'
alias sl='ls'
alias ruby='ruby1.9.3'
alias irb='irb1.9.3'
alias python='python3'
alias slrn-grc='slrn -h news.grc.com -f .jnewsrc-grc -i .slrnrc-grc'
alias slrn-old='slrn -h nntp.olduse.net -f .jnewsrc-olduse -i .slrnrc-olduse'
alias bboard='ssh -t anthonyg@faeroes.sdf.org bboard'
alias com='ssh -t anthonyg@sverige com'
