# .tmux.conf File
# By Anthony Giacalone
# anthonyg@sdf.org

#--General-Settings-------------------------------------------------------------
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set-option -ga terminal-overrides ",screen-256color:Tc"
set -g status-interval 1
set -g mouse on
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'

#--Key-Bindings-----------------------------------------------------------------
set -g prefix C-a
bind-key C-a last-window
bind-key C-h previous-window
bind-key C-n next-window
bind-key C-c new-window
bind-key C-d detach

bind | split-window -h
bind _ split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
# l is for last window by default; kept as-is to preserve that behavior
#bind l select-pane -R

#--Usability--------------------------------------------------------------------
set-option -g status-keys vi
set-window-option -g mode-keys vi
set -g display-time 3000
set -g set-titles on
setw -g automatic-rename on

#--Theme (night owl)------------------------------------------------------------
set-option -g status "on"
set -g status-bg "#112630"
set -g status-fg "#d6deeb"

set-window-option -g window-status-style bg="#011627",fg="#112630"
set-window-option -g window-status-activity-style bg="#82aaff",fg=colour248
set-window-option -g window-status-current-style fg="#011627",bg="#82aaff"

set-option -g pane-active-border-style fg="#637777"
set-option -g pane-border-style fg="#637777"

set-option -g message-style bg="#011627",fg="#82aaff"
set-option -g message-command-style bg="#011627",fg="#d6deeb"

set-option -g display-panes-active-colour colour250
set-option -g display-panes-colour colour237

set-window-option -g clock-mode-colour colour24

set-window-option -g window-status-bell-style fg=colour229,bg=colour88

set-option -g status-justify "left"
set-option -g status-left-length "80"
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

set-option -g status-left ""
set-option -g status-right "#[fg=#d6deeb,bg=#112630] %d-%b %H:%M #[fg=#011627,bg=#82aaff] #h "

set-window-option -g window-status-current-format "#[fg=#011627,bg=#82aaff] #I:#[fg=#011627,bg=#82aaff,bold] #W "
set-window-option -g window-status-format "#[fg=#d6deeb,bg=#112630] #I: #W "

#--Plugins----------------------------------------------------------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize the tmux plugin manager **MUST BE AT BOTTOM!**
run '~/.tmux/plugins/tpm/tpm'
