#!/bin/bash

# rm-ad: small utility to delete files (adverts) from within a zip archive.


sudo chmod 774 "$1"
sudo chown plex:plex "$1"

zip -d "$1" \
	*ZoU*.jpg \
	*zSoU-Nerd.jpg \
	*ZZ*.jpg \
	*zz*.jpg \
	*zTLK*.jpg \
	*gpcdguy*.jpg \
	*zWater*.jpg \
	*zOrions*.jpg \
	*xBluntmanx.jpg \
	*zzdelirium_dargh.png \

